Multi well validation
ome/ome-ngff-validator pull request #14
Opened 2022-10-17 15:04 UTC by will-moore

Currently, when validating a Plate, we only validate the First image in each Well and there's no way to validate other Images except to open each Well in turn.

This PR allows you to choose a Well Index to validate and also allows you to validate ALL Wells in a Plate.
However, this can result in loading a lot of data, so it's not the default behaviour.

To test, use `?source=https://cellpainting-gallery.s3.amazonaws.com/cpg0004-lincs/broad/images/2016_04_01_a549_48hr_batch1/images_zarr/SQ00014814__2016-05-23T17_24_56-Measurement1.ome.zarr/`

2022-10-18 08:25 UTC, sbesson requested changes
Thanks @will-moore. As discussed yesterday, I think it's valuable to have an option that allows the traversal of the entire metadata graph even if it's not necessarily on by default given the number of requests.

I find the current text confusing as it mixing the message for the current validation and the link for a different parameter in the same line. At first glance, I read it  "Validating 384 wells and images in index:0 only" and thought I had hit the wrong URL i.e. it's really easy to omit the middle of the sentence.

2022-10-18 16:32 UTC, will-moore commented
@sbesson Thanks - Hopefully this is better: 

![Screenshot 2022-10-18 at 17 31 34](https://user-images.githubusercontent.com/900055/196489572-52d42974-0ed2-4811-b166-ecd92221732f.png)

2022-10-19 12:58 UTC, sbesson approved these changes

2022-10-20 07:57 UTC, merged

2022-10-24 10:38 UTC, joshmoore commented
<img width="1884" alt="Screen Shot 2022-10-24 at 12 38 18" src="https://user-images.githubusercontent.com/88113/197507788-f02b68ae-a19d-487d-8b43-cdc78dff1641.png">

I :heart: the "all images" visualization. :)